openapi: 3.0.3
info:
  title: Team Service API
  version: 1.0.0
  description: API for managing teams and their members.

paths:
  /teams/getAllTeams:
    get:
      summary: Get All Teams
      description: get all teams
      operationId: getAllTeams
      tags:
        - Teams
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamDTO'
  /teams/getAllTeamsWithUsers:
    get:
      summary: Get All Teams with their users
      description: get all teams with their users
      operationId: getAllTeamsWithUsers
      tags:
        - Teams
      responses:
        '200':
          description: List of teams with their users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamWithUsersDTO'
  /teams/createTeam:
    post:
      summary: Create a new team
      description: Create a new team with the given team name and creator.
      operationId: createTeam
      tags:
        - Teams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeamRequest'
      responses:
        '201':
          description: Team created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTeamResponse'
        '400':
          description: Invalid input

  /teams/{team_id}/add_user:
    post:
      summary: Add a user to a team
      description: Add a user to a specific team by providing their user ID.
      operationId: addUserToTeam
      tags:
        - Teams
      parameters:
        - name: team_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddUserRequest'
      responses:
        '200':
          description: User added to the team successfully
        '404':
          description: Team or User not found
  /teams/{team_id}/remove_user:
    delete:
      summary: remove a user from a team
      description: Remove a user from a specific team by providing their user ID.
      operationId: removeUserFromTeam
      tags:
        - Teams
      parameters:
        - name: team_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveUserRequest'
      responses:
        '200':
          description: User removed from the team successfully
        '404':
          description: Team or User not found
  /teams/my-teams:
    get:
      summary: Get User Teams
      description: Retrieve the list of teams associated with the currently authenticated user.
      tags:
        - Teams
      operationId: getUserTeams
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamDTO'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  schemas:
    TeamDTO:
      type: object
      properties:
        id:
          type: string
          example: "team_123"
        name:
          type: string
          example: "Development Team"
        description:
          type: string
          example: "Team responsible for backend development"
        created_by:
          type: integer
    CreateTeamRequest:
      type: object
      properties:
        team_name:
          type: string
          description: Name of the team
        created_by:
          type: integer
          description: User ID of the creator
        description:
          type: string
          example: "Team responsible for backend development"
      required:
        - team_name
        - created_by

    CreateTeamResponse:
      type: object
      properties:
        team_id:
          type: integer
          description: Unique identifier of the created team
        team_name:
          type: string
          description: Name of the created team
    AddUserRequest:
      type: object
      properties:
        user_id:
          type: integer
          description: User ID of the user to be added
      required:
        - user_id
    RemoveUserRequest:
      type: object
      properties:
        user_id:
          type: integer
          description: User ID of the user to be added
      required:
        - user_id

    UserInTeamDTO:
      type: object
      properties:
        user_id:
          type: integer
        user_name:
          type: string

    TeamWithUsersDTO:
      type: object
      properties:
        team:
          $ref: '#/components/schemas/TeamDTO'
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserInTeamDTO'


