openapi: 3.0.3
info:
  title: Authentication Service API
  version: 1.0.0
  description: APIs for user registration, login, and logout with JWT authentication

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
  /auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /auth/refresh:
    post:
      summary: Refresh Access Token
      description: Refreshes the access token using a valid refresh token.
      operationId: refreshToken
      tags:
        - Authentication
      security:
        - bearerAuth: [ ]  # Requires a valid refresh token in the Authorization header
      requestBody:
        description: The request does not require a body, as the refresh token is sent in the Authorization header.
        content:
          application/json:
            schema:
              type: object
              example: { }  # No request body is needed
      responses:
        "200":
          description: Successfully refreshed access token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "400":
          description: Invalid or missing refresh token
        "401":
          description: Unauthorized - Refresh token is expired or invalid
        "500":
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        name:
          type: string
        role_id:
          type: integer
          default: 1
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        user_id:
          type: integer
        access_token:
          type: string
        refresh_token:
          type: string
        name:
          type: string
        role:
          type: string
        email:
          type: string
        status:
          type: string
